export default function Dashboard() {
  return (
    <div>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
      <h1>One</h1>
      <h2>TWO</h2>
    </div>
  );
}
